[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
shared.workspace = true

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
derive-new.workspace = true
serde.workspace = true
sqlx.workspace = true
strum.workspace = true
uuid.workspace = true
