name: CI for book
on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - "README.md"
      - "frontend/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable

      - name: Install cargo-related tools
        uses: taiki-e/install-action@005f9c234df66b748f0b5f22b26ef83172082762
        with:
          tool: nextest,cargo-make

      - name: Tests compile
        run: cargo make prepare-ci

      - name: Test
        run: cargo make test-ci

      - name: Clippy
        run: cargo make clippy-ci -- -Dwarnings

      - name: Rustfmt
        run: cargo make fmt -- --check
